# Generated by Django 5.0.6 on 2024-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderpart_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="В обработке", max_length=255, verbose_name="Статус заказа"
            ),
        ),
    ]
