# Generated by Django 5.0.6 on 2024-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_process", "В обработке"),
                    ("completed", "Выполнен"),
                    ("declined", "Отменен"),
                    ("return", "Возврат"),
                    ("postpone", "Отложен"),
                    ("has_defect", "Есть брак"),
                ],
                default="in_process",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
