# Generated by Django 5.0.6 on 2024-11-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новый"),
        ),
    ]
