# Generated by Django 5.0.6 on 2024-11-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_first_name_alter_order_last_name_and_more"),
        ("orders", "0006_alter_order_is_new"),
    ]

    operations = []
