# Generated by Django 5.0.6 on 2024-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="video_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
