# Generated by Django 5.0.6 on 2024-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0002_part_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
