# Generated by Django 5.0.6 on 2024-10-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("part", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="part.part",
                verbose_name="запчасти",
            ),
        ),
    ]
