# Generated by Django 5.0.6 on 2024-11-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новый"),
        ),
    ]
