# Generated by Django 5.0.6 on 2024-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_new",
            field=models.BooleanField(default=True, verbose_name="Новый"),
        ),
    ]
