# Generated by Django 5.0.6 on 2024-11-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options"),
        ("accounts", "0005_alter_user_is_new"),
    ]

    operations = []
