# Generated by Django 5.0.6 on 2024-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_0004_alter_user_options_0005_alter_user_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
