# Generated by Django 5.0.6 on 2024-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
