# Generated by Django 5.0.6 on 2024-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contactrequest_email_contactrequest_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactrequest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новый"),
        ),
    ]
