# Generated by Django 5.0.6 on 2024-11-12 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contactrequest_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата запроса",
            ),
            preserve_default=False,
        ),
    ]
