# Generated by Django 5.0.6 on 2024-11-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contactrequest_options"),
        ("contacts", "0005_contactrequest_created_at"),
    ]

    operations = []
