# Generated by Django 5.0.6 on 2024-09-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_part_amount_cart'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
