# Generated by Django 5.0.6 on 2024-09-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_part_price_pricehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
