# Generated by Django 5.1.1 on 2024-09-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='webapp.order', verbose_name='заказ'),
            preserve_default=False,
        ),
    ]
