# Generated by Django 5.0.6 on 2024-10-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_review"),
        ("webapp", "0012_alter_order_user"),
    ]

    operations = []
