# Generated by Django 5.0.6 on 2024-10-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_orderpart_quantity_alter_orderpart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненная корзина',
                'verbose_name_plural': 'Сохраненные корзины',
                'db_table': 'save_cart',
            },
        ),
        migrations.CreateModel(
            name='SaveCartPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_parts', to='webapp.savecart', verbose_name='Сохраненная корзина')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_parts', to='webapp.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Часть сохраненной корзины',
                'verbose_name_plural': 'Части сохраненной корзины',
                'db_table': 'save_cart_part',
                'unique_together': {('cart', 'part')},
            },
        ),
    ]
