# Generated by Django 5.0.6 on 2024-10-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_order_options_alter_orderpart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
