# Generated by Django 5.0.6 on 2024-10-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_alter_pricehistory_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
