# Generated by Django 5.0.6 on 2024-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_alter_pricehistory_price_delete_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpart",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderpart",
            name="part",
        ),
        migrations.RemoveField(
            model_name="orderpart",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderPart",
        ),
    ]
