# Generated by Django 5.0.6 on 2024-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0022_news_favorite_favorite_unique_user_favorite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinfo",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("passenger", "Легковые автомобили"),
                    ("truck", "Грузовые автомобили"),
                    ("special", "Спецтехника"),
                    ("bus", "Автобусы"),
                    ("engine", "Двигатели"),
                    ("railroad", "Ж/Д техника"),
                    ("bicycle", "Мотоциклы"),
                ],
                max_length=50,
            ),
        ),
    ]
