# Generated by Django 5.0.6 on 2024-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0023_alter_vehicleinfo_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engine",
            name="displacement",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
