# Generated by Django 5.0.6 on 2024-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0025_alter_vehicleinfo_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbrand",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carbrand",
            name="description_ko",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carbrand",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carbrand",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carbrand",
            name="name_ko",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carbrand",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="name_ko",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ko",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ko",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="body_type_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="body_type_ko",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="body_type_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
