name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Add environ
        run: cp .env.test ./source/.env
      - name: Migrations load
        run: |
          docker compose run -T --rm web bash -c "ls ../ && cd /app && python manage.py makemigrations --merge --noinput && python manage.py migrate"

  publish:
    needs: tests
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run publish
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd ${{ secrets.WORK_DIR }}
            echo "" > ./source/.env
            echo TEST="TEST" >> ./source/.env
            echo DATABASE_URL="psql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}" >> ./source/.env
            
            # Сброс локальных изменений перед git pull
            git reset --hard HEAD
            git clean -fdx
            
            git pull
            exit
